# Generated by Django 4.1.3 on 2022-11-17 14:51

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0002_alter_conteudo_corpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='youtube',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
