# Generated by Django 4.1.3 on 2022-11-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0003_conteudo_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='conteudo',
            name='categoria',
            field=models.CharField(default='Geral', max_length=255),
        ),
    ]
